"""Train a no-skip optical/electronic student model on CI-1 DWI slices.

中文说明：
这个脚本在 CI-1 的 DWI 二维切片上训练无跳跃连接的光学-电子学生网络，
输入是单通道 DWI 图像，输出是二值病灶分割 mask。

This is the CI-1 DWI counterpart of unet_student2_noskip_32ch.py:
- Input: one-channel DWI PNG slices generated by convert_ci1_dwi_to_2d.py
- Optical encoder: 32 trainable kernels
- Electronic decoder: no skip connections
- Output: binary lesion mask
"""

from __future__ import annotations

import argparse
import csv
import os
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import DataLoader
from tqdm import tqdm


@dataclass
class CI1DwiNoSkip32Config:
    manifest_path: Path = Path("data") / "ci1_dwi_2d_dedup" / "manifest.csv"
    output_dir: Path = Path("results") / "ci1_dwi_student_noskip_32ch"
    batch_size: int = 8
    num_epochs: int = 40
    learning_rate: float = 1e-3
    train_split: float = 0.8
    split_seed: int = 42
    num_workers: int = 0
    image_height: int = 256
    image_width: int = 256
    num_kernels: int = 32
    save_predictions_every: int = 5
    torch_threads: int | None = None
    torch_interop_threads: int | None = None
    bce_weight: float = 1.0
    dice_weight: float = 1.0


def read_manifest_rows(manifest_path: Path) -> list[dict[str, str]]:
    with manifest_path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def split_manifest_rows_by_patient(
    rows: Sequence[dict[str, str]],
    train_split: float,
    seed: int,
) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    patients = sorted({row["patient"] for row in rows})
    if len(patients) < 2:
        raise ValueError("Need at least two patients for patient-level train/val split.")

    rng = random.Random(seed)
    rng.shuffle(patients)
    train_count = int(len(patients) * train_split)
    train_count = min(max(train_count, 1), len(patients) - 1)
    train_patients = set(patients[:train_count])

    train_rows = [row for row in rows if row["patient"] in train_patients]
    val_rows = [row for row in rows if row["patient"] not in train_patients]
    return train_rows, val_rows


class CI1DwiSliceDataset(torch.utils.data.Dataset):
    def __init__(
        self,
        manifest_path: Path,
        rows: Sequence[dict[str, str]] | None,
        image_height: int,
        image_width: int,
    ) -> None:
        self.manifest_path = manifest_path
        self.rows = list(rows) if rows is not None else read_manifest_rows(manifest_path)
        self.image_height = image_height
        self.image_width = image_width

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
        row = self.rows[index]
        image = Image.open(row["image_path"]).convert("L")
        mask = Image.open(row["mask_path"]).convert("L")

        image = image.resize((self.image_width, self.image_height), Image.BILINEAR)
        mask = mask.resize((self.image_width, self.image_height), Image.NEAREST)

        image_array = np.asarray(image, dtype=np.float32) / 255.0
        mask_array = (np.asarray(mask, dtype=np.float32) > 127.0).astype(np.float32)

        image_tensor = torch.from_numpy(image_array).unsqueeze(0)
        mask_tensor = torch.from_numpy(mask_array).unsqueeze(0)
        return image_tensor, mask_tensor


class CI1DwiTensorCacheDataset(torch.utils.data.Dataset):
    def __init__(
        self,
        manifest_path: Path,
        rows: Sequence[dict[str, str]] | None,
    ) -> None:
        self.manifest_path = manifest_path
        self.rows = list(rows) if rows is not None else read_manifest_rows(manifest_path)

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
        row = self.rows[index]
        sample = torch.load(row["tensor_path"], map_location="cpu", weights_only=False)
        image = sample["image"].float()
        mask = sample["mask"].float()
        return image, mask


def manifest_uses_tensor_cache(rows: Sequence[dict[str, str]]) -> bool:
    return bool(rows) and "tensor_path" in rows[0]


def configure_torch_threads(
    torch_threads: int | None,
    torch_interop_threads: int | None,
) -> None:
    if torch_threads is not None:
        if torch_threads < 1:
            raise ValueError("--torch-threads must be >= 1.")
        torch.set_num_threads(torch_threads)

    if torch_interop_threads is not None:
        if torch_interop_threads < 1:
            raise ValueError("--torch-interop-threads must be >= 1.")
        torch.set_num_interop_threads(torch_interop_threads)


class OpticalElectronicCI1DwiNoSkip32(nn.Module):
    def __init__(
        self,
        image_height: int,
        image_width: int,
        in_channels: int = 1,
        num_kernels: int = 32,
        out_channels: int = 1,
    ) -> None:
        super().__init__()
        self.image_height = image_height
        self.image_width = image_width
        self.num_kernels = num_kernels
        self.sensor_size = (max(1, image_height // 8), max(1, image_width // 8))
        self.decoder_size1 = (max(1, image_height // 4), max(1, image_width // 4))
        self.decoder_size2 = (max(1, image_height // 2), max(1, image_width // 2))
        self.decoder_size3 = (image_height, image_width)

        self.optical_kernels = nn.Parameter(
            torch.randn(num_kernels, in_channels, 3, 3) * 0.01
        )

        self.up1_conv = nn.Conv2d(num_kernels, 24, kernel_size=3, padding=1)
        self.up1_bn = nn.BatchNorm2d(24)
        self.up2_conv = nn.Conv2d(24, 16, kernel_size=3, padding=1)
        self.up2_bn = nn.BatchNorm2d(16)
        self.up3_conv = nn.Conv2d(16, out_channels, kernel_size=3, padding=1)

    @staticmethod
    def upsample_kernel(kernel_3x3: torch.Tensor) -> torch.Tensor:
        return F.interpolate(kernel_3x3, size=(6, 6), mode="nearest")

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        kernels = self.upsample_kernel(self.optical_kernels)
        x_downsampled = F.adaptive_avg_pool2d(x, self.sensor_size)
        bottleneck = F.conv2d(x_downsampled, kernels, padding=2, bias=None)

        up1 = F.interpolate(
            bottleneck, size=self.decoder_size1, mode="bilinear", align_corners=False
        )
        up1 = F.relu(self.up1_bn(self.up1_conv(up1)))

        up2 = F.interpolate(
            up1, size=self.decoder_size2, mode="bilinear", align_corners=False
        )
        up2 = F.relu(self.up2_bn(self.up2_conv(up2)))

        up3 = F.interpolate(
            up2, size=self.decoder_size3, mode="bilinear", align_corners=False
        )
        return self.up3_conv(up3)


def count_parameters(model: nn.Module) -> int:
    return sum(parameter.numel() for parameter in model.parameters() if parameter.requires_grad)


def calculate_dice(logits: torch.Tensor, masks: torch.Tensor, threshold: float = 0.5) -> float:
    return calculate_binary_metrics(logits, masks, threshold=threshold).dice


def calculate_iou(logits: torch.Tensor, masks: torch.Tensor, threshold: float = 0.5) -> float:
    return calculate_binary_metrics(logits, masks, threshold=threshold).iou


@dataclass
class BinaryMetrics:
    dice: float
    iou: float
    positive_dice: float
    positive_iou: float
    total_slices: int
    positive_mask_slices: int
    empty_mask_slices: int
    predicted_positive_slices: int


def calculate_binary_metrics(
    logits: torch.Tensor,
    masks: torch.Tensor,
    threshold: float = 0.5,
) -> BinaryMetrics:
    preds = (torch.sigmoid(logits) > threshold).float()
    intersection = (preds * masks).sum(dim=(1, 2, 3))
    pred_area = preds.sum(dim=(1, 2, 3))
    mask_area = masks.sum(dim=(1, 2, 3))
    denominator = pred_area + mask_area
    union = ((preds + masks) > 0).float().sum(dim=(1, 2, 3))

    dice = (2.0 * intersection + 1e-7) / (denominator + 1e-7)
    iou = (intersection + 1e-7) / (union + 1e-7)
    has_mask = mask_area > 0
    positive_count = int(has_mask.sum().item())
    empty_count = int((~has_mask).sum().item())
    predicted_positive_count = int((pred_area > 0).sum().item())

    if positive_count:
        positive_dice = float(dice[has_mask].mean().item())
        positive_iou = float(iou[has_mask].mean().item())
    else:
        positive_dice = 0.0
        positive_iou = 0.0

    return BinaryMetrics(
        dice=float(dice.mean().item()),
        iou=float(iou.mean().item()),
        positive_dice=positive_dice,
        positive_iou=positive_iou,
        total_slices=int(logits.shape[0]),
        positive_mask_slices=positive_count,
        empty_mask_slices=empty_count,
        predicted_positive_slices=predicted_positive_count,
    )


@dataclass
class BinaryMetricAccumulator:
    dice_sum: float = 0.0
    iou_sum: float = 0.0
    positive_dice_sum: float = 0.0
    positive_iou_sum: float = 0.0
    total_slices: int = 0
    positive_mask_slices: int = 0
    empty_mask_slices: int = 0
    predicted_positive_slices: int = 0

    def update(self, logits: torch.Tensor, masks: torch.Tensor) -> None:
        metrics = calculate_binary_metrics(logits, masks)
        self.dice_sum += metrics.dice * metrics.total_slices
        self.iou_sum += metrics.iou * metrics.total_slices
        self.positive_dice_sum += metrics.positive_dice * metrics.positive_mask_slices
        self.positive_iou_sum += metrics.positive_iou * metrics.positive_mask_slices
        self.total_slices += metrics.total_slices
        self.positive_mask_slices += metrics.positive_mask_slices
        self.empty_mask_slices += metrics.empty_mask_slices
        self.predicted_positive_slices += metrics.predicted_positive_slices

    def compute(self) -> BinaryMetrics:
        total = max(self.total_slices, 1)
        positive_total = max(self.positive_mask_slices, 1)
        return BinaryMetrics(
            dice=self.dice_sum / total,
            iou=self.iou_sum / total,
            positive_dice=self.positive_dice_sum / positive_total,
            positive_iou=self.positive_iou_sum / positive_total,
            total_slices=self.total_slices,
            positive_mask_slices=self.positive_mask_slices,
            empty_mask_slices=self.empty_mask_slices,
            predicted_positive_slices=self.predicted_positive_slices,
        )


class BCEDiceLoss(nn.Module):
    def __init__(self, bce_weight: float = 1.0, dice_weight: float = 1.0) -> None:
        super().__init__()
        self.bce_weight = bce_weight
        self.dice_weight = dice_weight
        self.bce = nn.BCEWithLogitsLoss()

    def forward(self, logits: torch.Tensor, masks: torch.Tensor) -> torch.Tensor:
        bce_loss = self.bce(logits, masks)
        probs = torch.sigmoid(logits)
        intersection = (probs * masks).sum(dim=(1, 2, 3))
        denominator = probs.sum(dim=(1, 2, 3)) + masks.sum(dim=(1, 2, 3))
        dice = (2.0 * intersection + 1e-7) / (denominator + 1e-7)
        dice_loss = 1.0 - dice.mean()
        return self.bce_weight * bce_loss + self.dice_weight * dice_loss


def get_loaders(config: CI1DwiNoSkip32Config) -> tuple[DataLoader, DataLoader]:
    rows = read_manifest_rows(config.manifest_path)
    train_rows, val_rows = split_manifest_rows_by_patient(
        rows,
        train_split=config.train_split,
        seed=config.split_seed,
    )

    if manifest_uses_tensor_cache(rows):
        train_dataset = CI1DwiTensorCacheDataset(
            manifest_path=config.manifest_path,
            rows=train_rows,
        )
        val_dataset = CI1DwiTensorCacheDataset(
            manifest_path=config.manifest_path,
            rows=val_rows,
        )
    else:
        train_dataset = CI1DwiSliceDataset(
            manifest_path=config.manifest_path,
            rows=train_rows,
            image_height=config.image_height,
            image_width=config.image_width,
        )
        val_dataset = CI1DwiSliceDataset(
            manifest_path=config.manifest_path,
            rows=val_rows,
            image_height=config.image_height,
            image_width=config.image_width,
        )

    train_loader = DataLoader(
        train_dataset,
        batch_size=config.batch_size,
        shuffle=True,
        num_workers=config.num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=config.batch_size,
        shuffle=False,
        num_workers=config.num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    return train_loader, val_loader


@torch.no_grad()
def visualize_predictions(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    output_path: Path,
    num_samples: int = 6,
    show_probability: bool = True,
) -> None:
    model.eval()
    positive_samples: list[tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]] = []
    fallback_samples: list[tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]] = []

    for images, masks in loader:
        images = images.to(device)
        logits = model(images)
        probs = torch.sigmoid(logits)
        preds = probs > 0.5

        images_cpu = images.cpu()
        masks_cpu = masks.cpu()
        probs_cpu = probs.cpu()
        preds_cpu = preds.cpu()
        has_mask = masks_cpu.flatten(1).sum(dim=1) > 0

        for index in range(images_cpu.shape[0]):
            sample = (
                images_cpu[index : index + 1],
                masks_cpu[index : index + 1],
                probs_cpu[index : index + 1],
                preds_cpu[index : index + 1],
            )
            if bool(has_mask[index]):
                positive_samples.append(sample)
            else:
                fallback_samples.append(sample)

        if len(positive_samples) >= num_samples:
            break

    selected_samples = (positive_samples + fallback_samples)[:num_samples]
    if not selected_samples:
        return

    images = torch.cat([sample[0] for sample in selected_samples], dim=0)
    masks = torch.cat([sample[1] for sample in selected_samples], dim=0)
    probs = torch.cat([sample[2] for sample in selected_samples], dim=0)
    preds = torch.cat([sample[3] for sample in selected_samples], dim=0)
    num_samples = images.shape[0]
    num_columns = 4 if show_probability else 3

    fig, axes = plt.subplots(num_samples, num_columns, figsize=(3 * num_columns, 3 * num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    for index in range(num_samples):
        axes[index, 0].imshow(images[index, 0].numpy(), cmap="gray")
        axes[index, 0].set_title("DWI")
        axes[index, 0].axis("off")
        axes[index, 1].imshow(masks[index, 0].numpy(), cmap="gray")
        axes[index, 1].set_title("Mask")
        axes[index, 1].axis("off")
        prediction_column = 2
        if show_probability:
            axes[index, 2].imshow(probs[index, 0].numpy(), cmap="magma", vmin=0.0, vmax=1.0)
            axes[index, 2].set_title("Probability")
            axes[index, 2].axis("off")
            prediction_column = 3
        axes[index, prediction_column].imshow(preds[index, 0].numpy(), cmap="gray")
        axes[index, prediction_column].set_title("Prediction")
        axes[index, prediction_column].axis("off")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


@torch.no_grad()
def visualize_optical_kernels(model: OpticalElectronicCI1DwiNoSkip32, output_path: Path) -> None:
    kernels = F.interpolate(model.optical_kernels.detach().cpu(), size=(6, 6), mode="nearest")

    fig, axes = plt.subplots(4, 8, figsize=(16, 8))
    for index in range(model.num_kernels):
        row, col = index // 8, index % 8
        ax = axes[row, col]
        kernel = kernels[index, 0].numpy()
        vmax = max(abs(float(kernel.min())), abs(float(kernel.max())), 1e-8)
        ax.imshow(kernel, cmap="RdBu_r", vmin=-vmax, vmax=vmax)
        ax.set_title(f"K{index:02d}", fontsize=8)
        ax.axis("off")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.suptitle("CI-1 DWI no-skip optical kernels", fontsize=12)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    epoch: int,
) -> tuple[float, BinaryMetrics]:
    model.train()
    total_loss, num_batches = 0.0, 0
    metric_accumulator = BinaryMetricAccumulator()

    for images, masks in tqdm(loader, desc=f"Epoch {epoch}"):
        images = images.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)
        optimizer.zero_grad(set_to_none=True)
        logits = model(images)
        loss = criterion(logits, masks)
        loss.backward()
        optimizer.step()

        total_loss += float(loss.item())
        metric_accumulator.update(logits.detach(), masks)
        num_batches += 1

    return total_loss / num_batches, metric_accumulator.compute()


@torch.no_grad()
def validate(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
) -> tuple[float, BinaryMetrics]:
    model.eval()
    total_loss, num_batches = 0.0, 0
    metric_accumulator = BinaryMetricAccumulator()

    for images, masks in tqdm(loader, desc="Validating"):
        images = images.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)
        logits = model(images)
        loss = criterion(logits, masks)
        total_loss += float(loss.item())
        metric_accumulator.update(logits, masks)
        num_batches += 1

    return total_loss / num_batches, metric_accumulator.compute()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train CI-1 DWI no-skip 32ch student.")
    parser.add_argument("--manifest-path", type=Path, default=CI1DwiNoSkip32Config.manifest_path)
    parser.add_argument("--output-dir", type=Path, default=CI1DwiNoSkip32Config.output_dir)
    parser.add_argument("--epochs", type=int, default=CI1DwiNoSkip32Config.num_epochs)
    parser.add_argument("--batch-size", type=int, default=CI1DwiNoSkip32Config.batch_size)
    parser.add_argument("--lr", type=float, default=CI1DwiNoSkip32Config.learning_rate)
    parser.add_argument("--height", type=int, default=CI1DwiNoSkip32Config.image_height)
    parser.add_argument("--width", type=int, default=CI1DwiNoSkip32Config.image_width)
    parser.add_argument("--num-workers", type=int, default=CI1DwiNoSkip32Config.num_workers)
    parser.add_argument("--bce-weight", type=float, default=CI1DwiNoSkip32Config.bce_weight)
    parser.add_argument("--dice-weight", type=float, default=CI1DwiNoSkip32Config.dice_weight)
    parser.add_argument(
        "--torch-threads",
        type=int,
        default=CI1DwiNoSkip32Config.torch_threads,
        help="Limit PyTorch CPU intra-op threads. Leave unset to use PyTorch default.",
    )
    parser.add_argument(
        "--torch-interop-threads",
        type=int,
        default=CI1DwiNoSkip32Config.torch_interop_threads,
        help="Limit PyTorch CPU inter-op threads. Leave unset to use PyTorch default.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    configure_torch_threads(
        torch_threads=args.torch_threads,
        torch_interop_threads=args.torch_interop_threads,
    )
    config = CI1DwiNoSkip32Config(
        manifest_path=args.manifest_path,
        output_dir=args.output_dir,
        batch_size=args.batch_size,
        num_epochs=args.epochs,
        learning_rate=args.lr,
        num_workers=args.num_workers,
        image_height=args.height,
        image_width=args.width,
        torch_threads=args.torch_threads,
        torch_interop_threads=args.torch_interop_threads,
        bce_weight=args.bce_weight,
        dice_weight=args.dice_weight,
    )

    config.output_dir.mkdir(parents=True, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    print(f"Torch CPU threads: {torch.get_num_threads()}")
    print(f"Torch inter-op threads: {torch.get_num_interop_threads()}")
    print(f"Manifest: {config.manifest_path}")
    print(f"Output: {config.output_dir}")

    train_loader, val_loader = get_loaders(config)
    print(f"Train slices: {len(train_loader.dataset)}")
    print(f"Val slices:   {len(val_loader.dataset)}")

    model = OpticalElectronicCI1DwiNoSkip32(
        image_height=config.image_height,
        image_width=config.image_width,
        in_channels=1,
        num_kernels=config.num_kernels,
        out_channels=1,
    ).to(device)
    print(f"Trainable params: {count_parameters(model):,}")
    print(f"Sensor size: {model.sensor_size}")

    criterion = BCEDiceLoss(
        bce_weight=config.bce_weight,
        dice_weight=config.dice_weight,
    )
    print(f"Loss: BCE*{config.bce_weight:g} + Dice*{config.dice_weight:g}")
    optimizer = torch.optim.Adam(model.parameters(), lr=config.learning_rate)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="max", factor=0.5, patience=5
    )

    best_dice = 0.0
    best_state = None
    best_epoch = -1

    for epoch in range(1, config.num_epochs + 1):
        train_loss, train_metrics = train_one_epoch(
            model, train_loader, criterion, optimizer, device, epoch
        )
        val_loss, val_metrics = validate(model, val_loader, criterion, device)
        scheduler.step(val_metrics.positive_dice)

        print(
            f"Epoch {epoch:03d} | "
            f"train loss {train_loss:.4f} "
            f"iou {train_metrics.iou:.4f} dice {train_metrics.dice:.4f} "
            f"pos_iou {train_metrics.positive_iou:.4f} pos_dice {train_metrics.positive_dice:.4f} | "
            f"val loss {val_loss:.4f} "
            f"iou {val_metrics.iou:.4f} dice {val_metrics.dice:.4f} "
            f"pos_iou {val_metrics.positive_iou:.4f} pos_dice {val_metrics.positive_dice:.4f} "
            f"pred_pos {val_metrics.predicted_positive_slices}/{val_metrics.total_slices}"
        )

        if val_metrics.positive_dice > best_dice:
            best_dice = val_metrics.positive_dice
            best_state = {key: value.detach().cpu() for key, value in model.state_dict().items()}
            best_epoch = epoch
            torch.save(
                {
                    "epoch": epoch,
                    "model_state_dict": best_state,
                    "val_dice": val_metrics.dice,
                    "val_iou": val_metrics.iou,
                    "val_positive_dice": val_metrics.positive_dice,
                    "val_positive_iou": val_metrics.positive_iou,
                    "val_positive_mask_slices": val_metrics.positive_mask_slices,
                    "val_predicted_positive_slices": val_metrics.predicted_positive_slices,
                    "config": {
                        "image_height": config.image_height,
                        "image_width": config.image_width,
                        "num_kernels": config.num_kernels,
                        "manifest_path": str(config.manifest_path),
                        "bce_weight": config.bce_weight,
                        "dice_weight": config.dice_weight,
                    },
                },
                config.output_dir / "ci1_dwi_student_noskip_32ch_best.pth",
            )
            print(
                f"[OK] Saved best checkpoint from epoch {epoch} "
                f"positive Dice={val_metrics.positive_dice:.4f}"
            )
            visualize_predictions(
                model,
                val_loader,
                device,
                config.output_dir / "predictions_best.png",
            )

        if epoch == 1 or epoch % config.save_predictions_every == 0:
            visualize_predictions(
                model,
                val_loader,
                device,
                config.output_dir / f"predictions_epoch_{epoch:03d}.png",
            )

    if best_state is not None:
        model.load_state_dict(best_state)
        visualize_optical_kernels(
            model,
            config.output_dir / "ci1_dwi_student_noskip_32ch_optical_kernels.png",
        )
        print(f"Best epoch: {best_epoch}, positive Dice={best_dice:.4f}")


if __name__ == "__main__":
    main()
